# Generated by Django 5.2.5 on 2025-08-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loveapp', '0002_video_remove_photo_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
        migrations.RemoveField(
            model_name='video',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='video',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
